<?php

function default_panels_install(){
  //enable the default panel template
  variable_set('panels_everywhere_site_template_enabled', TRUE);

  //default shortcuts
  $shortcuts = shortcut_default_set();
  $shortcuts->links[] = array(
    'link_path' => 'admin/structure/pages/nojs/operation/page-homepage/handlers/page_homepage_panel_context/content',
    'link_title' => 'Edit Homepage',
  );
  $shortcuts->links[] = array(
    'link_path' => 'admin/structure/pages/nojs/operation/site_template/handlers/site_template_panel_context_4/content',
    'link_title' => 'Edit Sitewide Panels',
  );
  shortcut_set_save($shortcuts);
}